services:
  mongo:
    image: mongo
    container_name: mongoLocal
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    volumes:
      - .docker/mongodb/data/db/:/data/db/
      - .docker/mongodb/data/log/:/var/log/mongodb/
